### PR TITLE
update ss3 repo names;

### PR DESCRIPTION
**Pull request by e-perl-NOAA**
@k-doering-NOAA the model files will need updating after next release, looks like they haven't been updated since v.3.30.18.
Creating PR in prep for changing ss3 repo names ahead of moving over to GHEC - see ss3 issue [#542](https://github.com/nmfs-stock-synthesis/stock-synthesis/issues/524). Doesn't need to be merged until after we change the repo names with the next release.

Some actions might fail since repo names haven't changed yet.

### CODE REVIEW

**Comment by e-gugliotti-NOAA** [comment]
@k-doering-NOAA, some of these workflow tests are failing and I'm not sure why, looks like maybe it's an issue with pak? I've had various issues with pak in the past so it wouldn't surprise me.

**Comment by k-doering-NOAA** [comment]
It looks like 2 of the pkgs SSMSE depends on were removed from CRAN 🤦🏻‍♀️ https://cran.r-project.org/web/packages/assertive.properties/index.html

**Comment by k-doering-NOAA** [comment]
@e-perl-NOAA should this be merged now? Or are any changes needed?

**Comment by e-perl-NOAA** [comment]
@k-doering-NOAA it should be good now!

**Pull request closed without merging**
